fctransfer: FileTransferWinch Class Reference
FileTransferWinch Class Reference abstract
Data Structures
class FileTransferAbortedException
This exception indicates that transfer was aborted; I have not yet clarified in the API whether this exception would take precidence over FileTransferDataTransferException if both occur, or a FileTransferDataTransferException causes a FileTransferAbortedException.
class FileTransferChecksumMismatchException
This exception alerts to the specific Data Transfer issuesuch that the receiver's checksum confirmation did not match the sender ...
class FileTransferDataTransferException
This exception alerts to issues during transfer of data: connection lost, etc ...
class FileTransferIllegalFSMReplyException
This exception indicates that the underlying Finite State Machine received an unexpected reply, and has no next-state in the conversation.
class FileTransferWinchException
A base collector exception: "there was some exception in the FileTransferWinch class"; typically, more meaning and/or usefulness is reached by catching specific subclasses of this exception.
Public Member Functions
String getHost ()
String getPass ()
String getPath ()
String getUser ()
String name ()
abstract boolean upload (File file, Vector< String > uploadNotify) throws FileTransferWinchException
upload a file using this FileTransferWinch; errors in upload are handled via Exceptions
boolean upload (String file, Vector< String > uploadNotify) throws FileTransferWinchException
upload a file using this FileTransferWinch; errors in upload are handled via Exceptions
Static Public Member Functions
static String checksum (File file) throws java.security.NoSuchAlgorithmException, java.io.FileNotFoundException, java.io.IOException
Calculate an MD5 checksum.
static String checksum (String file) throws java.security.NoSuchAlgorithmException, java.io.FileNotFoundException, java.io.IOException
Calculate an MD5 checksum.
static String[] examples (java.net.URL url)
list one or more example URLs showing the available upload/download protocols
static boolean handles (java.net.URL u)
static String MD5toString (byte[] digest)
convert a MD5 digest to a printable string.
Protected Attributes
java.net.URL url = null
Detailed Description
Definition at line 6 of file FileTransferWinch.java.
Member Function Documentation
static String checksum (File file) throws java.security.NoSuchAlgorithmException, java.io.FileNotFoundException, java.io.IOException inline static
Calculate an MD5 checksum.
In converting this file from VIFieldTool code, the checksum stuff was already here, so my logic was "why make a user search for checksumming tools?" The resulting algorithm generates a checksum compatible with the "md5" and "md5sum" tools available in everything non-Windows everywhere. It's like "hey, why not include a checksum piece with everything?"
So in this function, given a filename, opens it up and reads in data blocks, incorporating each against the MD5 digest: stirring the pot-of-MD5 with blocks of bytes to generate the final checksum digest.
This file itself may have no testcases, but this function is confirmed against the build platform's md5 or md5sum program for accuracy.
Parameters
file filename of the file to calculate
Returns
checksum, as a string
Definition at line 275 of file FileTransferWinch.java.
References FileTransferWinch.MD5toString().
Referenced by FileTransferWinch.checksum(), FTP4J.upload(), and ApacheCommonsNetSFTP.upload().
static String checksum (String file) throws java.security.NoSuchAlgorithmException, java.io.FileNotFoundException, java.io.IOException inline static
Calculate an MD5 checksum.
So in this function, given a filename, it passes execution to the checksum(File) function do do the actual work.
Parameters
file filename of the file to calculate
Returns
checksum, as a string
Definition at line 304 of file FileTransferWinch.java.
References FileTransferWinch.checksum().
static String [] examples (java.net.URL url) inline static
list one or more example URLs showing the available upload/download protocols
Parameters
url a sample URL showing user/pass/pathname
Returns
array of examples using that URL
Definition at line 25 of file FileTransferWinch.java.
static String MD5toString (byte[] digest) inline static
convert a MD5 digest to a printable string.
Part of "hey, why not include a checksum piece with everything?"
Public/Static because, hey, it might be useful elsewhere, and needs no state
Parameters
digest the resulting MD5 digest to convert to a string
Returns
string representation of the digest
Definition at line 243 of file FileTransferWinch.java.
Referenced by FileTransferWinch.checksum().
abstract boolean upload (File file, Vector< String > uploadNotify) throws FileTransferWinchException abstract
upload a file using this FileTransferWinch; errors in upload are handled via Exceptions
Parameters
file the content to upload
uploadNotify array of identifiers (email address or jabber contacts) to list as notify recipients in the upload checksum file
Returns
true if upload was checksum-certified; false is such facility isn't available (error if checksum is available and mismatches)
Referenced by FileTransferWinch.upload().
boolean upload (String file, Vector< String > uploadNotify) throws FileTransferWinchException inline
upload a file using this FileTransferWinch; errors in upload are handled via Exceptions
Parameters
file the content to upload
uploadNotify array of identifiers (email address or jabber contacts) to list as notify recipients in the upload checksum file
Returns
true if upload was checksum-certified; false is such facility isn't available (error if checksum is available and mismatches)
Definition at line 44 of file FileTransferWinch.java.
References FileTransferWinch.upload().
The documentation for this class was generated from the following file:
java/FileTransferWinch.java